"""add_portfolio_artifact_id_to_course_instance

Revision ID: 68259462e2ea
Revises: b7d4e2f19a03
Create Date: 2026-03-06 12:31:57.081604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68259462e2ea'
down_revision: Union[str, Sequence[str], None] = 'b7d4e2f19a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_instances', sa.Column('portfolio_artifact_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'course_instances', 'portfolio_artifacts', ['portfolio_artifact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_instances', type_='foreignkey')
    op.drop_column('course_instances', 'portfolio_artifact_id')
    # ### end Alembic commands ###
